cabal-version: 3.0
name: words
version: 0.1.0.0
license: BSD-3-Clause
license-file: LICENSE
copyright: Tony Day (c) 2025
category: text
author: Tony Day
maintainer: tonyday567@gmail.com
homepage: https://github.com/tonyday567/words#readme
bug-reports: https://github.com/tonyday567/words/issues
synopsis: Word counting as a circuits laboratory.
description: R&D journal. Word counting as a circuits laboratory.
build-type: Simple
tested-with:
  ghc ==9.10.1
  ghc ==9.12.2
  ghc ==9.14.1

extra-doc-files:
  readme.md

source-repository head
  type: git
  location: https://github.com/tonyday567/words

common ghc-options-stanza
  ghc-options:
    -Wall
    -Wcompat
    -Widentities
    -Wincomplete-record-updates
    -Wincomplete-uni-patterns
    -Wpartial-fields
    -Wredundant-constraints

common ghc2024-additions
  default-extensions:
    DataKinds
    DerivingStrategies
    DisambiguateRecordFields
    ExplicitNamespaces
    GADTs
    LambdaCase
    MonoLocalBinds
    RoleAnnotations

common ghc2024-stanza
  if impl(ghc >=9.10)
    default-language:
      GHC2024
  else
    import: ghc2024-additions
    default-language:
      GHC2021

library
  import: ghc-options-stanza
  import: ghc2024-stanza
  hs-source-dirs: src
  build-depends:
    base >=4.14 && <5,
    bytestring,
    circuits,
    circuits-meter,
    circuits-parser,
    containers >=0.6 && <0.9,
    deepseq,
    text,

  exposed-modules:
    Words

  ghc-options: -O2

